<?php
require_once ("database_object.php");
require_once ("database.php");
class Member extends DatabaseObject
{
    public $id;
    public $password;
    public $first_name;
    public $last_name;
    public $image_file;
    public $email;
    public $description;
    public $temp_path;
    protected static $table_name = "members";
    protected static $db_fields = array('id', 'first_name', 'last_name', 'password');
    public $errors=array();
    protected $upload_errors = array(
        UPLOAD_ERR_OK           => "No errors.",
        UPLOAD_ERR_INI_SIZE     => "Larger than upload_max_filesize.",
        UPLOAD_ERR_FORM_SIZE    => "Larger than MAX_FILE_SIZE",
        UPLOAD_ERR_PARTIAL      => "Patal upload.",
        UPLOAD_ERR_NO_FILE      => "No file.",
        UPLOAD_ERR_NO_TMP_DIR   => "No temporary directory.",
        UPLOAD_ERR_CANT_WRITE   => "Can't write to disk.",
        UPLOAD_ERR_EXTENSION    => "File upload stopped by extension"
    );
    public static function construct_with_args($id, $password, $first_name, $last_name)
    {
        $object = new self;
        $object->first_name = $first_name;
        $object->last_name = $last_name;
        $object->password = $password;
        $object->id = $id;
        return $object;
    }
    // We should update the uploads.member_id table first (member id is a forign key)
    public function update($current_id){
        global $database;
        $attributes = $this->get_sanitized_attributes();
        $attribute_pairs = array();
        foreach($attributes as $key => $value){
            if($key == 'id') { $attribute_pairs[] = "{$key}={$value}"; }
            else { $attribute_pairs[] = "{$key}='{$value}'"; }
        }
        $sql = "UPDATE ". static::$table_name ." SET ";
        $sql .= join(", ", $attribute_pairs);
        $sql .= " WHERE id=" . $database->escape_value($current_id);
        $database->query($sql);
        return($database->affected_rows() == 1)? true : false;

    }

    public static function search($query)
    {
        parent::search($query); // TODO: Change the autogenerated stub
        global $database;
        $query = trim($query);
        if (mb_strlen($query)===0){
            // no need for empty search right?
            return false;
        }

        $query = static::limitChars($query);

        // Weighing scores
        $scoreFullTitle = 6;
        $scoreTitleKeyword = 5;
        $scoreFullSummary = 5;
        $scoreSummaryKeyword = 4;


        $keywords = static::filterSearchKeys($query);
        $escQuery = $database->escape_value($query);
        $first_name = array();
        $last_name = array();

        /** Matching full occurences **/
        if (count($keywords) > 1){
            $first_name[] = "if (first_name LIKE '%".$escQuery."%',{$scoreFullTitle},0)";
            $last_name[] = "if (last_name LIKE '%".$escQuery."%',{$scoreFullSummary},0)";
        }
        /** Matching Keywords **/
        foreach($keywords as $key){
            $first_name[] = "if (first_name LIKE '%".$database->escape_value($key)."%',{$scoreTitleKeyword},0)";
            $last_name[] = "if (last_name LIKE '%".$database->escape_value($key)."%',{$scoreSummaryKeyword},0)";
        }

        $sql = "SELECT *,
            (
                (-- Title score
                ".implode(" + ", $first_name)."
                )+
                (-- Summary
                ".implode(" + ", $last_name)."
                )
            ) as relevance
            FROM members
            HAVING relevance > 0
            order by relevance Desc";
        $results = static::find_by_sql($sql);
        if (count($results) <= 0){
            return false;
        }
        return $results;


    }
}
?>
